# -*- coding: utf-8 -*-
"""APIDataToCSV.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yeinb2PCGctMtR-ffSl11jK3RxxYmr6s
"""

!sudo -H pip install cython pystan numpy pandas
!sudo -H pip install fbprophet

import requests 
import csv
import json
import datetime
import pprint as pp
url = "https://api.darksky.net/forecast/"
appid = "your API key"
location="Latitude, Longitude"
time="Starting time of data collection"
# Sending HTTP request to get data
res = requests.get("https://api.darksky.net/forecast/" + appid + "/" + location + "," + time + "?&extend=hourly&units=si&exclude=currently,alerts,flags,daily")
# Display the HTTP response code
print( res.status_code ) # 200 means success
# Put the text into json format
data = json.loads( res.text )

# Building of CSV file with data of first request
csvData = [['name','time','temperature']]
a=0
with open('output.csv', 'w', newline='') as csvFile:
  writer = csv.writer(csvFile)
  writer.writerows(csvData)
  for i in data['hourly']['data']:
    try:
      print (i['time'],i['temperature'])
    except KeyError:
      print (i['time'],[''])
    try:
      writer.writerow(['Temperature',i['time'],i['temperature']])
    except KeyError:
      writer.writerow(['Temperature',i['time'],''])
    a=i['time']
csvFile.close()

# Get the timestamp of today's 00:00UTC
dt = datetime.datetime.now().timestamp()
dt = dt - dt%86400

# Write the temperature data between starting time and today into CSV
while a<dt:
  res = requests.get("https://api.darksky.net/forecast/" + appid + "/" + location + "," +str(a) + "?&extend=hourly&units=si&exclude=currently,alerts,flags,daily")
  data = json.loads( res.text )
  with open('output.csv', 'a', newline='') as csvfile:
    writer = csv.writer(csvfile)
    for i in data['hourly']['data']:
      try:
        print (i['time'],i['temperature'])
      except KeyError:
        print (i['time'],[''])
      try:
        writer.writerow(['Temperature',i['time'],i['temperature']])
      except KeyError:
        writer.writerow(['Temperature',i['time'],''])
  # Increment the date by 1
  a=i['time']
  a=(int(a/86400)+1)*86400
  csvFile.close()

# If you want to print the data
#with open('output.csv', newline='') as csvfile:
#  rows = csv.reader(csvfile)
#  for row in rows:
#    print(row)

# Download the CSV file
from google.colab import files
files.download("output.csv")