# -*- coding: utf-8 -*-
"""Weather Forecast Facebook Prophet with Dark Sky historical data.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZNcgGG3_p2dDndTCzs30syaX7mZCVN6x
"""

from google.colab import files
#Upload the data
uploaded = files.upload()

import pandas as pd
import numpy as np
from fbprophet import Prophet

df = pd.read_csv('output.csv')
df['ds'] = df['time']
df['y'] = df['temperature']
df = df.drop(['name', 'time', 'temperature'], axis=1)
df.head()
model = Prophet()
model.fit(df)
future = model.make_future_dataframe(periods=24*9, freq='H')
future.tail(48)
forecast = model.predict(future)
model.plot(forecast)
model.plot_components(forecast)
print(forecast)


from IPython.display import display, HTML
####Code for printing the full forecast table
#print("Dataframe 1:")
#display(forecast)
#print("Dataframe 2:")
#display(HTML(forecast.to_html()))

####Simplifying the forecast table
forecastsimple=forecast[['ds', 'yhat', 'yhat_lower', 'yhat_upper']]
#display(HTML(forecastsimple.to_html()))
forecastsimple.to_excel("result.xlsx")
####To download the forecast table
files.download('result.xlsx') 

####Three years forecast
#model3 = Prophet()
#model3.fit(df)
#future3 = model3.make_future_dataframe(periods=24*365*3, freq='H')
#forecast3 = model3.predict(future3)
#model3.plot(forecast3)
#model3.plot_components(forecast3)
#forecast3simple=forecast3[['ds', 'yhat', 'yhat_lower', 'yhat_upper']]
#forecast3simple.to_excel("result3Years.xlsx")
#files.download('result3Years.xlsx') 
